# Generated by Django 6.1 on 2026-08-27 20:39

from django.db import migrations

BUILDINGS = [
    {"id": 1, "name": "Milan HQ"},
    {"id": 2, "name": "Building B"},
]

ROOMS = [
    {"id": 1, "name": "Meeting room A", "building_id": 1},
    {"id": 2, "name": "Meeting room B", "building_id": 1},
    {"id": 3, "name": "Room 101", "building_id": 1},
    {"id": 4, "name": "Conference Room", "building_id": 2},
]

BOOKINGS = [
    {"id": 1, "room_id": 1, "date": "2025-07-15", "start_time": "10:00", "end_time": "11:00", "booked_by": "Team standup"},
    {"id": 2, "room_id": 1, "date": "2025-07-15", "start_time": "13:00", "end_time": "15:00", "booked_by": "Project review"},
    {"id": 3, "room_id": 2, "date": "2025-07-15", "start_time": "09:00", "end_time": "12:00", "booked_by": "Workshop"},
    {"id": 4, "room_id": 2, "date": "2025-07-15", "start_time": "14:00", "end_time": "16:00", "booked_by": "1:1 meetings"},
]


def seed_buildings(apps, schema_editor):
    Building = apps.get_model("bookings", "Building")
    for data in BUILDINGS:
        Building.objects.update_or_create(id=data["id"], defaults=data)


def unseed_buildings(apps, schema_editor):
    Building = apps.get_model("bookings", "Building")
    Building.objects.filter(id__in=[b["id"] for b in BUILDINGS]).delete()


def seed_rooms(apps, schema_editor):
    Room = apps.get_model("bookings", "Room")
    for data in ROOMS:
        Room.objects.update_or_create(id=data["id"], defaults=data)


def unseed_rooms(apps, schema_editor):
    Room = apps.get_model("bookings", "Room")
    Room.objects.filter(id__in=[r["id"] for r in ROOMS]).delete()


def seed_bookings(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    for data in BOOKINGS:
        Booking.objects.update_or_create(id=data["id"], defaults=data)


def unseed_bookings(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    Booking.objects.filter(id__in=[b["id"] for b in BOOKINGS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_buildings, unseed_buildings),
        migrations.RunPython(seed_rooms, unseed_rooms),
        migrations.RunPython(seed_bookings, unseed_bookings),
    ]
