# Generated by Django 6.1 on 2026-08-28

from django.core.management.color import no_style
from django.db import migrations


def reset_sequences(apps, schema_editor):
    """
    0002_seed_bookings inserted Building/Room/Booking rows with explicit
    `id` values. Postgres identity sequences only advance on inserts that
    omit `id`, so after that migration each sequence was still at its
    starting value while the tables already held rows up to id=4 —
    the next ORM-created row would collide on the primary key.
    """
    Building = apps.get_model("bookings", "Building")
    Room = apps.get_model("bookings", "Room")
    Booking = apps.get_model("bookings", "Booking")

    style = no_style()
    for model in (Building, Room, Booking):
        sql = schema_editor.connection.ops.sequence_reset_sql(style, [model])
        for statement in sql:
            schema_editor.execute(statement)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_bookings'),
    ]

    operations = [
        migrations.RunPython(reset_sequences, noop),
    ]
